var movies =['salar', 'animal', 'baubali', 'pushpa', 'oye']
movies.push ('pokiri', 'maharshi')
movies.push ('jaanu')
movies.push('aarya')
console.log(movies)
console.log(movies.length)
movies.pop('aarya')
console.log(movies)
console.log(movies.length)
movies.push('aarya')
console.log(movies)
movies.push('65')
console.log(movies)
movies.unshift('varsham')
console.log(movies)
movies.shift('varsham')
console.log(movies)
console.log(movies.slice(1,4))
console.log(movies.length)     